# dataset
dataset: aerialhistory
mask_format: supervisely
label_dict:  # values should be [1, 2, 3, ..., N]
    'house': 1
# num_classes: inferred from label_dict

# inference directory
in_infer_dir: data/AerialHistory
in_infer_img_dir: Image
in_infer_img_suffix: .png
out_infer_mask_dir: Pred
out_infer_mask_suffix: .json

# visualization parameters
category_palette:
    1: [150, 223, 228, 64]  # blue
