# dataset
dataset: ambo

label_dict:  # values should be [1, 2, 3, ..., N]
    'house': 1
int_dict: null

# inference directory
in_infer_dir: data/Ambo
in_infer_img_dir: Image
in_infer_img_suffix: .png
in_infer_img_list: infer1

# output directory
out_mask_dir: data/Ambo/Pred
