# dataset
dataset: googlestaticmap
label_dict:  # values should be [1, 2, 3, ..., N]
    'house': 1
int_dict: null
num_classes: 2  # including background

# inference directory
in_infer_dir: data/GoogleStaticMap
in_infer_img_dir: Image
in_infer_img_suffix: .png

# output directory
out_mask_dir: data/AerialHistory/Pred

# visualization directory
out_visual_dir: data/AerialHistory/Visual

# visualization parameters
category_palette:
    1: [255, 36, 0, 64]  # red
