# dataset
dataset: googleearthpro
mask_format: supervisely
label_dict:  # values should be [1, 2, 3, ..., N]
    'N/A': 1
    'Unfinished House': 2
    'Tin Roof': 3
    'Colored Roof': 4
# num_classes: inferred from label_dict

# data loader
train_ratio: 0.85  # null if train.txt and val.txt exist

# trainval directory
in_tv_dir: data/GoogleEarthPro
in_tv_img_dir: Image
in_tv_img_suffix: .jpg
in_tv_mask_dir: Mask
in_tv_mask_suffix: .jpg.json

# output directory
out_mask_dir: data/Pred

# visualization directory
out_visual_dir: data/Visual

# visualization parameters
category_palette:
    1: [255, 255, 255, 64] # white
    2: [255, 36, 0, 64] # red
    3: [150, 223, 228, 64] # blue
    4: [255, 213, 0, 64] # yellow