# dataset
dataset: Mexico
label_dict:  # values should be [1, 2, 3, ..., N]
    'house': 1
int_dict: null

# inference directory
in_infer_dir: data/MexicoInequality
in_infer_img_dir: Image
in_infer_img_suffix: .png
in_infer_img_list: null

# output directory
out_mask_dir: data/MexicoInequality/Pred

# visualization directory
out_visual_dir: data/MexicoInequality/Visual

# visualization parameters
category_palette:
    1: [135, 206, 235, 64]  # sky blue
