# dataset
dataset: Mexico
mask_format: supervisely
label_dict:  # values should be [1, 2, 3, ..., N]
    'house': 1
int_dict: null

# # data loader
# train_ratio: 0.01  # null if train.txt and val.txt exist

# # trainval directory
# in_tv_dir: data/Mexico
# in_tv_img_dir: Image
# in_tv_img_suffix: .png
# in_tv_mask_dir: Mask
# in_tv_mask_suffix: .png.json

# inference directory
in_infer_dir: data/Mexico
in_infer_img_dir: Image
in_infer_img_suffix: .png
in_infer_img_list: null

# output directory
out_mask_dir: data/Mexico/Pred

# visualization directory
out_visual_dir: data/Mexico/Visual

# visualization parameters
category_palette:
    1: [135, 206, 235, 64]  # sky blue
