# dataset
dataset: openaitanzania
mask_format: openaitanzania
# label_dict:  # values should be [1, 2, 3, ..., N]
#     'Foundation': 1
#     'Incomplete': 2
#     'Complete': 3
# num_classes: inferred from label_dict
label_dict: {'1': 1, '2': 2, '3': 3, '4': 4, '5': 5, '6': 6, '7': 7, '8': 8, '9': 9, '10': 10, '11': 11, '12': 12, '13': 13, '14': 14, '15': 15, '16': 16, '17': 17, '18': 18, '19': 19, '20': 20, '21': 21, '22': 22, '23': 23, '24': 24, '25': 25, '26': 26, '27': 27, '28': 28, '29': 29, '30': 30, '31': 31, '32': 32, '33': 33, '34': 34, '35': 35, '36': 36, '37': 37, '38': 38, '39': 39, '40': 40, '41': 41, '42': 42, '43': 43, '44': 44, '45': 45, '46': 46, '47': 47, '48': 48, '49': 49, '50': 50, '51': 51, '52': 52, '53': 53, '54': 54, '55': 55, '56': 56, '57': 57, '58': 58, '59': 59, '60': 60, '61': 61, '62': 62, '63': 63, '64': 64, '65': 65, '66': 66, '67': 67, '68': 68, '69': 69, '70': 70, '71': 71, '72': 72, '73': 73, '74': 74, '75': 75, '76': 76, '77': 77, '78': 78, '79': 79, '80': 80, '81': 81, '82': 82, '83': 83, '84': 84, '85': 85, '86': 86, '87': 87, '88': 88, '89': 89, '90': 90}

# data loader
train_ratio: 0.85  # null if train.txt and val.txt exist

# trainval directory
in_tv_dir: data/OpenAITanzania
in_tv_img_dir: Image
in_tv_img_suffix: .png
in_tv_mask_dir: Mask
in_tv_mask_suffix: .json

# output directory
out_mask_dir: data/OpenAITanzania/Pred

# visualization directory
out_visual_dir: data/OpenAITanzania/Visual

# visualization parameters
category_palette:
    1: [255, 36, 0, 64]  # red
    2: [150, 223, 228, 64]  # blue
    3: [255, 213, 0, 64] # yellow
