# dataset
dataset: openaitanzania
mask_format: openaitanzania
label_dict:  # values should be [1, 2, 3, ..., N]
    'Foundation': 0
    'Incomplete': 1
    'Complete': 1
int_dict:
    1: 'house'
num_classes: 2  # including background

# data loader
train_ratio: 0.9  # null if train.txt and val.txt exist

# trainval directory
in_tv_dir: data/OpenAITanzania
in_tv_img_dir: Image
in_tv_img_suffix: .png
in_tv_mask_dir: Mask
in_tv_mask_suffix: .json

# output directory
out_mask_dir: data/OpenAITanzania/Pred

# visualization directory
out_visual_dir: data/OpenAITanzania/Visual

# visualization parameters
category_palette:
    1: [135, 206, 235, 64]  # sky blue
