# dataset
dataset: openaitanzania
mask_format: openaitanzania
label_dict:  # values should be [1, 2, 3, ..., N]
    'Foundation': 1
    'Incomplete': 2
    'Complete': 3
# num_classes: inferred from label_dict

# data loader
train_ratio: 0.9  # null if train.txt and val.txt exist

# trainval directory
in_tv_dir: data/OpenAITanzania
in_tv_img_dir: Image
in_tv_img_suffix: .png
in_tv_mask_dir: Mask
in_tv_mask_suffix: .json

# output directory
out_mask_dir: data/OpenAITanzania/Pred

# visualization directory
out_visual_dir: data/OpenAITanzania/Visual

# visualization parameters
category_palette:
    1: [255, 36, 0, 64]  # red
    2: [150, 223, 228, 64]  # blue
    3: [255, 213, 0, 64] # yellow
