# dataset
dataset: siaya2
mask_format: supervisely
label_dict:  # values should be [1, 2, 3, ..., N]
    'house': 1
int_dict: null

# # data loader
# train_ratio: 0.8  # null if train.txt and val.txt exist

# inference directory
in_infer_dir: data/Siaya2
in_infer_img_dir: Image
in_infer_img_suffix: .png
in_infer_img_list: null

# # trainval directory
# in_tv_dir: data/GiveDirectly
# in_tv_img_dir: Image
# in_tv_img_suffix: .png
# in_tv_mask_dir: Mask
# in_tv_mask_suffix: .png.json

# output directory
out_mask_dir: data/Siaya2/Pred

# visualization directory
out_visual_dir: data/Siaya2/Visual

# visualization parameters
category_palette:
    1: [150, 223, 228, 64] # blue
    # 2: [223, 150, 228, 64]
    # 3: [228, 223, 150, 64]
