# dataset
dataset: test
mask_format: supervisely
label_dict:  # values should be [1, 2, 3, ..., N]
    'people': 1
    'dog': 2
# num_classes: inferred from label_dict

# data loader
train_ratio: 0.5  # null if train.txt and val.txt exist

# trainval directory
in_tv_dir: data/Test
in_tv_img_dir: Image
in_tv_img_suffix: .jpg
in_tv_mask_dir: Mask
in_tv_mask_suffix: .jpg.json

# inference directory
in_infer_dir: data/Test
in_infer_img_dir: Image
in_infer_img_suffix: .jpg

# output directory
out_mask_dir: data/Pred

# visualization directory
out_visual_dir: data/Visual

# visualization parameters
category_palette:
    1: [255, 36, 0, 64]  # red
    2: [150, 223, 228, 64]  # blue
