# trainval directory
in_trainval_dir: data/GoogleEarthPro
in_trainval_img_dir: Image
in_trainval_mask_dir: Mask

# model and log directory
runs_dir: runs/

# inference directory
in_infer_dir: data/GoogleEarthPro/Image

# visualization directory
in_visual_dir: data/GoogleEarthPro
in_visual_img_dir: Image
in_visual_mask_dir: Mask
out_visual_dir: output/GoogleEarthPro

# data loader
dataset: googleearthpro
train_val_init: True
train_ratio: 0.85
label_dict: # values should be [1,2,3,...,N]
    'N/A': 1
    'Unfinished House': 2
    'Tin Roof': 3
    'Colored Roof': 4
# num_classes is inferred from label_dict

# training data augmentation params
random_crop_height: 1 # (0, 1], ratio of random crop
random_crop_width: 1 # (0, 1], ratio of random crop
brightness: 0.1
contrast: 0.1
saturation: 0.1
hue: 0.1
vertical_flip: 0.5
horizontal_flip: 0.5
resize_height: 500 # size of tensors fed into Mask R-CNN
resize_width: 500 # size of tensors fed into Mask R-CNN

# training schedule
epochs: 200
eval_epoch: 150
batch_size_per_gpu: 3
num_workers: 2
# num_gpus inferred from torch.cuda.device_count()

# model parameters
coco_pretrained: True

# optimizer parameters
lr: 0.0001
lr_scheduler_step_size: 50
lr_scheduler_gamma: 0.1

# evaluation parameters
mask_threshold: 0.5
key_metric_name: mAP

# visualization parameters
prob_train_visualization: 0.1
category_palette:
    1: [255, 255, 255, 64] # white: N/A
    2: [255, 36, 0, 64] # red: Unfinished House
    3: [150, 223, 228, 64] # blue: Tin Roof
    4: [255, 213, 0, 64] # yellow: Colored Roof
bbox_outline: [255, 255, 255, 255] # white
label_fill: [255, 255, 255, 255] # white
up_scale: 2 # to improve visualization quality
font: utils/fonts/helvetica-light.ttf
font_size: 25
