# trainval directory
in_trainval_dir: data/GoogleEarthPro
in_trainval_img_dir: Image
in_trainval_mask_dir: Mask

# inference directory
in_infer_dir: data/GoogleEarthPro/Image

# visualization directory
in_visual_dir: data/GoogleEarthPro
in_visual_img_dir: Image
in_visual_mask_dir: Mask
out_visual_dir: output/GoogleEarthPro

# data loader
dataset: googleearthpro
label_dict: # values should be [1,2,3,...,N]
    'N/A': 1
    'Unfinished House': 2
    'Tin Roof': 3
    'Colored Roof': 4
# num_classes is inferred from label_dict

# training data augmentation params
random_crop_height: 1 # (0, 1], ratio of random crop
random_crop_width: 1 # (0, 1], ratio of random crop
brightness: 0.2
contrast: 0.2
saturation: 0.2
hue: 0.2
vertical_flip: 0.6
horizontal_flip: 0.6
resize_height: 400 # size of tensors fed into Mask R-CNN
resize_width: 400 # size of tensors fed into Mask R-CNN

# training schedule
epochs: 2
batch_size_per_gpu: 1
num_workers: 0
# num_gpus inferred from torch.cuda.device_count()

# model parameters
coco_pretrained: False

# optimizer parameters
lr: 0.001

# visualization parameters
category_palette:
    1: [255, 255, 255, 64] # white: N/A
    2: [255, 36, 0, 64] # red: Unfinished House
    3: [150, 223, 228, 64] # blue: Tin Roof
    4: [255, 213, 0, 64] # yellow: Colored Roof
bbox_outline: [255, 255, 255, 255] # white
label_fill: [255, 255, 255, 255] # white
up_scale: 2 # to improve visualization quality
font: utils/fonts/helvetica-light.ttf
font_size: 25
